### ISSUE TITLE
Unable to connect to 'ssl://gateway.sandbox.push.apple.com:2195': (0)

### ISSUE THREAD

**Issue by phaeton2040** [bryglen/yii-apns-gcm#1]
Error when trying Yii::app()->apns->send() method. 
Tried to use solution from here - https://github.com/duccio/ApnsPHP/issues/29
It didn't work for me.

**Comment by bryglen** [comment]
Pem file is invalid or the port is blocked

**Comment by phaeton2040** [comment]
Thanks for the reply. 
How to make a valid pem file? I've got two files, public and private keys. And a passphrase for private key.
Port is not blocked. Checked with openssl utility

**Comment by phaeton2040** [comment]
Do I need to set 'ProviderCertificatePassphrase' and 'RootCertificationAuthority' in 'options' section in 'main.php' ?

**Comment by bryglen** [comment]
you can try it. i'm not sure.. all I did is to create a Wrapper for Yii framework using https://github.com/duccio/ApnsPHP/

**Comment by thuey** [comment]
Just in case someone stumbles across this, calling setProviderCertificatePassphrase worked for me, after combining my cert and key files as described here http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1 under the "Making a PEM File" section.

**Comment by bryglen** [comment]
I am now closing this issue. it looks like that the issue is because of the PEM file and not the library itself
